apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ecommerce-app-deploy
  name: ecommerce-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-app-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ecommerce-app-deploy
    spec:
      containers:
      - image: saifullahmuhammad/ecommerceapp:v1
        name: ecommerceapp
        resources: {}
status: {}
